apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: gha-runner-scale-set-controller
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    namespace: arc-systems
    releaseName: gha-k8s-runner
    version: 0.9.3
    includeCRDs: true
    valuesFile: values.yaml
