{
 "title": "MoonkinMetrics - Scanner",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Total API Hits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(scan_requests_total{cached=\"false\"})",
     "legendFormat": "Non-Cached Requests"
    },
    {
     "expr": "sum(scan_api_attempts_total) - sum(scan_requests_total{cached=\"false\"})",
     "legendFormat": "API Hits"
    }
   ]
  },
  {
   "title": "API Hits Per Request (5m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(scan_api_attempts_total[$__interval])) / sum(increase(scan_requests_total{cached=\"false\"}[$__interval]))",
     "legendFormat": "API Hits Per Request (5m)"
    }
   ]
  },
  {
   "title": "Cache Rate of Succesful Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(scan_requests_total{success=\"true\", cached=\"true\"})",
     "legendFormat": "Cached"
    },
    {
     "expr": "sum(scan_requests_total{success=\"true\", cached=\"false\"})",
     "legendFormat": "Non-Cached"
    }
   ]
  },
  {
   "title": "Request Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(scan_requests_total{success=\"false\"})",
     "legendFormat": "Failures"
    },
    {
     "expr": "sum(scan_requests_total{success=\"true\"})",
     "legendFormat": "Successes"
    }
   ]
  },
  {
   "title": "Repair Rate of Successful Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum(scan_requests_total{success=\"true\", repaired=\"true\"})",
     "legendFormat": "Repaired"
    },
    {
     "expr": "sum(scan_requests_total{success=\"true\", repaired=\"false\"})",
     "legendFormat": "Non-Repaired"
    }
   ]
  },
  {
   "title": "Cache Rate of Succesful Requests [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(scan_requests_total{success=\"true\", cached=\"true\"}[$__interval]))",
     "legendFormat": "Cached"
    },
    {
     "expr": "sum(increase(scan_requests_total{success=\"true\", cached=\"false\"}[$__interval]))",
     "legendFormat": "Non-Cached"
    }
   ]
  },
  {
   "title": "Request Failure Rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(scan_requests_total{success=\"false\"}[$__interval]))",
     "legendFormat": "Failures"
    },
    {
     "expr": "sum(increase(scan_requests_total{success=\"true\"}[$__interval]))",
     "legendFormat": "Successes"
    }
   ]
  },
  {
   "title": "Repair Rate of Successful Requests [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(scan_requests_total{success=\"true\", repaired=\"true\"}[$__interval]))",
     "legendFormat": "Repaired"
    },
    {
     "expr": "sum(increase(scan_requests_total{success=\"true\", repaired=\"false\"}[$__interval]))",
     "legendFormat": "Non-Repaired"
    }
   ]
  }
 ]
}