{
 "title": "Moonkin Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(scan_cache_hits_total[$__rate_interval])",
     "legendFormat": "Cached"
    },
    {
     "expr": "increase((scan_requests_total - scan_successes_total)[$__rate_interval:])",
     "legendFormat": "Error"
    },
    {
     "expr": "increase((scan_successes_total - scan_cache_hits_total)[$__rate_interval:])",
     "legendFormat": "API Success"
    }
   ]
  },
  {
   "title": "API Errors Per Request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "avg_over_time((increase(scan_api_errors_total[$__rate_interval]) / (increase(scan_requests_total[$__rate_interval]) - increase(scan_cache_hits_total[$__rate_interval])))[1m:])",
     "legendFormat": "API Errors Per Request in 1m Window"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time((1.0 - increase(scan_successes_total[$__rate_interval]) / increase(scan_requests_total[$__rate_interval]))[5m:])",
     "legendFormat": "Failure Rate in 5m Window"
    }
   ]
  },
  {
   "title": "API Hits Per Request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg_over_time((increase(scan_api_hits_total[$__rate_interval]) / (increase(scan_requests_total[$__rate_interval]) - increase(scan_cache_hits_total[$__rate_interval])))[1m:])",
     "legendFormat": "API Hits Per Request in 1m Window"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time((increase(scan_cache_hits_total[$__rate_interval]) / increase(scan_requests_total[$__rate_interval]))[5m:])",
     "legendFormat": "Cache Hits In 5m Window"
    }
   ]
  }
 ]
}