name: Scan for US non solo shuffle data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

permissions:
  id-token: write
  contents: read

env:
  AWS_WOW_DATA_OBJECT: ${{ secrets.AWS_WOW_DATA_OBJECT }}
  WOW_CLIENT_ID: ${{ secrets.WOW_CLIENT_ID }}
  WOW_CLIENT_SECRET: ${{ secrets.WOW_CLIENT_SECRET }}

jobs:
  scan-bnet-api:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.1'
      - name: Run scanner
        run: |
          go run cmd/cli/cli.go --output ./wow talents
          go run cmd/cli/cli.go --output ./wow ladder --region us --bracket 2v2
          go run cmd/cli/cli.go --output ./wow ladder --region us --bracket 3v3
          go run cmd/cli/cli.go --output ./wow ladder --region us --bracket rbg
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: 'us-east-1'
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - name: Upload WoW data
        run: |
          aws s3 sync ./wow/ ${{ env.AWS_WOW_DATA_OBJECT}}
