name: Scan for US blitz data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

permissions:
  id-token: write
  contents: read

env:
  AWS_WOW_DATA_OBJECT: ${{ secrets.AWS_WOW_DATA_OBJECT }}
  WOW_CLIENT_ID: ${{ secrets.WOW_CLIENT_ID }}
  WOW_CLIENT_SECRET: ${{ secrets.WOW_CLIENT_SECRET }}

jobs:
  scan-bnet-api:
    runs-on: [gha-k8s-runner]
    env:
      CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.1'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: Test scanner
        run: go test -v ./...
      - name: Run scanner
        run: |
          go run cmd/cli/cli.go --cache-dir clean
          go run cmd/cli/cli.go --cache-dir /tmp --collector $NODE_IP:4317 --output ./wow ladder --region us --bracket blitz 
      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: 'us-east-1'
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - name: Upload WoW data
        if: github.ref == 'refs/heads/master'
        run: |
          aws s3 sync ./wow/ ${{ env.AWS_WOW_DATA_OBJECT }}
